### PR TITLE
made versions of dependencies constant

### PR DESCRIPTION
**Pull request by anishagg17**

### CODE REVIEW

**Comment by gopavasanth** [comment]
Hello @anishagg17

We just migrated VideoCutTool code repositories to Wikimedia Gerrit, So please send your patch to https://gerrit.wikimedia.org/r/#/admin/projects/labs/tools/VideoCutTool, You can take a look at What_is_Gerrit to know more about Gerrit.

**Comment by anishagg17** [comment]
Okay @gopavasanth

**Comment by gopavasanth** [comment]
Also, I'm not sure we really need to make the versions of dependencies constant, What are the benefits of this?

**Comment by anishagg17** [comment]
Sir,

Dependencies can unexpectedly introduce behaviour changes to app also Past builds cannot be reproduced perfectly

**Pull request closed without merging**
